### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YannisHeine** [persiafighter/Rocket-Jobs#1]
When u type /joinjob taxi or something else you get an error 

`An error occured while executing jjob [taxi]: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket_Jobs.CommandJoinApplyJob.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0
  at Rocket.Core.Commands.RocketCommandManager.Execute (IRocketPlayer player, System.String command) [0x00000] in <filename unknown>:0`

**Comment by persiafighter** [comment]
```
An error occured while executing joinjob [EMS]: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket_Jobs.CommandJoinApplyJob.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0 
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (IRocketPlayer player, System.String command) [0x00000] in <filename unknown>:0 
```
I had same error when I finally got time to test the plugin. Update the plugin on the server to the latest build (build #4) and try again.

**Comment by YannisHeine** [comment]
I already have the latest version

**Comment by persiafighter** [comment]
Well this error doesn't happen to me anymore. Does the group or job exist in the config?

**Comment by YannisHeine** [comment]
yes it exist (taxi)

**Comment by persiafighter** [comment]
It exists in the permission file as well? (i'm attempting to replicate the bug)

**Comment by YannisHeine** [comment]
oh no i dont have any permission group for it

**Comment by persiafighter** [comment]
You should create the permissions group for it. Not only that but this error is fixed in the latest build... I'll be adding at some point (I don't know why I didn't already) a version that will be logged on start... that way you can definitely know if your install is outdated or not.

**Comment by YannisHeine** [comment]
> [loading] RocketJobs
[registered] /acceptjob (Rocket_Jobs.CommandJobAccept/AcceptJob)
[registered] /aj (Rocket_Jobs.CommandJobAccept/AJ)
[registered] /ajob (Rocket_Jobs.CommandJobAccept/AJob)
[registered] /acceptj (Rocket_Jobs.CommandJobAccept/AcceptJ)
[registered] /jobadmin (Rocket_Jobs.CommandJobAdmin/JobAdmin)
[registered] /ja (Rocket_Jobs.CommandJobAdmin/JA)
[registered] /jadmin (Rocket_Jobs.CommandJobAdmin/JAdmin)
[registered] /joba (Rocket_Jobs.CommandJobAdmin/JobA)
[registered] /leavejob (Rocket_Jobs.CommandJobLeave/LeaveJob)
[registered] /ljob (Rocket_Jobs.CommandJobLeave/LJob)
[registered] /leavej (Rocket_Jobs.CommandJobLeave/LeaveJ)
[registered] /joinjob (Rocket_Jobs.CommandJoinApplyJob/JoinJob)
[registered] /jj (Rocket_Jobs.CommandJoinApplyJob/JJ)
[registered] /jjob (Rocket_Jobs.CommandJoinApplyJob/JJob)
[registered] /jobs (Rocket_Jobs.CommandJobs/Jobs)
[registered] /lj (Rocket_Jobs.CommandJobs/LJ)
[registered] /ljobs (Rocket_Jobs.CommandJobs/LJobs)
[registered] /listjobs (Rocket_Jobs.CommandJobs/ListJobs)
RocketJobs >> Jobs has been loaded!

**Comment by persiafighter** [comment]
>  I'll be adding at some point (I don't know why I didn't already) a version that will be logged on start

Not yet added. Try build #5, it has the version display added. Also try joining the job in build #5, it should work now without a problem.

**Comment by YannisHeine** [comment]
now i get no response on command

**Comment by persiafighter** [comment]
Check the console/log, something should've been outputted/said there.

**Comment by YannisHeine** [comment]
no there is nothing :/

**Comment by persiafighter** [comment]
Could you paste the logs in a pastebin so I can see?

**Comment by persiafighter** [comment]
no answer in 7+ days. Assuming issue was resolved. Closed.
