### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by Kakaokiller** [persiafighter/Rocket-Jobs#12]
What should I do when I have the dll file written in Visual Studio : in order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project.

**Comment by Pustalorc** [comment]
You are pressing the start button, that doesn't compile. That compiles AND runs. You cant run a dll. Do Build -> Build solution on the top bar instead. And please, use google for any issues you have whilst compiling.

**Comment by Kakaokiller** [comment]
My problem is, I still can't get the dll written down. Can you send me a web page or a video on how do I do it? Please. I'm having a hard time orienting.

**Comment by Kakaokiller** [comment]
OH, MY GOD. I can see how to... Thanks for your time and nerves xd
